name: project
description: CRM

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: any
  dio: ^4.0.0
  url_launcher: ^6.1.5
  flutter_libphonenumber: ^2.2.2
  rflutter_alert: ^2.0.7
  datetime_picker_formfield: ^2.0.0
  file_picker: ^8.0.6
  open_file: ^3.2.1
  path_provider: ^2.0.13
  flutter_downloader: ^1.5.2
  flutter_share: ^2.0.0
  percent_indicator: ^4.2.3
  clipboard: ^0.1.3
  cached_network_image: ^3.1.0+1
  flutter_portal: ^1.1.4
  google_maps_flutter: ^2.1.1
  geocoding: ^3.0.0
  custom_info_window: ^1.0.1
  flutter_local_notifications: ^17.2.1+2
  flutter_native_timezone: ^2.0.0
  flutter_app_badger: ^1.3.0
  pusher_client: ^2.0.0
  image_picker: ^1.1.2
  icon_badge: ^1.0.0
  permission_handler: ^11.3.1
  filesystem_picker: ^4.1.0
  basic_utils: ^5.5.4
  shared_preferences: ^2.0.7
  maps_launcher: ^2.0.1
#  location: ^4.3.0
  badges: ^3.1.2
  scrollable_positioned_list: ^0.3.8
  flutter_svg: ^2.0.9
  provider: ^6.0.1
  connectivity_plus: ^6.0.3
  get: ^4.6.1
  intl: ^0.19.0
  sleek_circular_slider: ^2.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  about: ^2.1.1
  avatar_glow: ^3.0.1
  animated_background: ^2.0.0
  geolocator: ^9.0.1
  flutter_masked_text2: ^0.9.1
#  pattern_formatter: ^2.0.0
  multi_select_flutter: ^4.0.0
  keyboard_actions: ^4.2.0
  delayed_display: ^2.0.0
  app_links: ^6.1.4
  geocode: ^1.0.3
  table_calendar: ^3.0.6
  multiselect: ^0.1.1
#  simple_moment: ^1.1.1
  fl_chart: ^0.68.0
  toggle_switch: ^2.0.1
  msix: ^3.6.3
  phone_state: ^1.0.2
  flutter_colorpicker: ^1.0.3
  material_floating_search_bar: ^0.3.7
  dropdown_button2: ^2.3.9
  flutter_tags: ^1.0.0-nullsafety.1
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage

  calendar_view: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  change_app_package_name: ^1.1.0
  map_launcher: ^3.3.1
  sticky_headers: ^0.3.0+2
  pie_chart: ^5.3.2
  numberpicker: ^2.1.1
  uni_links: ^0.5.1
  expandable: ^5.0.1
  focused_menu: ^1.0.5
  tab_container: ^3.5.3
  animations: ^2.0.7
  liquid_progress_indicator: ^0.4.0
  flutter_staggered_grid_view: ^0.7.0
  easy_localization: ^3.0.1
  logger: ^2.4.0
  stacked: ^3.0.1
  equatable: ^2.0.5

  flutter_staggered_animations: ^1.1.1
  animated_digit: ^3.2.1
  animated_text_kit: ^4.2.2
  animated_widgets: ^1.1.0
  sn_progress_dialog: ^1.1.2
  socket_io_client: ^2.0.1
  flutter_bloc: ^8.1.2
  flutter_widget_from_html: ^0.15.1
#  webcontent_converter: ^0.0.8
  pdf: ^3.8.4
  printing: ^5.9.3
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  bloc: ^8.1.1
  floating_action_bubble: ^1.1.4
  device_info_plus: ^10.1.0
  dio_logging_interceptor: ^1.0.1
  dio_http_cache_lts: ^0.4.1
  json_annotation: ^4.6.0
  flutter_otp_text_field: ^1.1.1
  mailer: ^6.0.1
  google_sign_in: ^6.1.0
  buttons_tabbar: ^1.3.9
  syncfusion_flutter_datagrid: ^28.1.39
#  webcontent_converter2: ^0.0.7+1
#  mapbox_gl: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  json_serializable: ^6.8.0
  dependency_validator: ^4.1.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/hytech_sun.png
    - assets/images/logo.png
    - assets/images/background_pattern.png
    - assets/images/Top.png
    - assets/images/Bottom.png
    - assets/images/top-detail.png
    - assets/images/top-detail-edit.png
    - assets/images/login.png
    - assets/images/top-user-profile.png
    - assets/images/agent.png
    - assets/images/default-avatar.png
    - assets/images/drawer-header.png
    - assets/images/chart2.svg
    - assets/images/animated/spinner.gif
    - assets/locations.json
    - assets/images/map_pin.png
    - assets/icons/app_icon.png
    - assets/images/hytech_icon.png
    - assets/images/animated/animation.gif
    - assets/map_states.json
    - assets/tickets/airplane_blue.png
    - assets/tickets/airplane_white.png
    - assets/tickets/barcode.png
    - assets/tickets/bg_blue.png
    - assets/tickets/logo_white.png
    - assets/tickets/planeroute_blue.png
    - assets/tickets/planeroute_white.png
    - assets/tickets/clock.png
    - assets/images/noevents.png
    - assets/images/leadsicon.png
    - assets/images/dealsicon.png
    - assets/images/propertiesicon.png
    - assets/images/contactsicon.png
    - assets/documentation/README.md
    - assets/documentation/CHANGELOG.html
    - assets/images/Hytech-Glitch.png
    - assets/images/no-event.svg
    - assets/images/no-event.png
    - lib/new_bloc/core/data/local/json_responses/
    - assets/images/animated/animated-bell.gif
    - assets/images/ios_logo.png
    - assets/images/android_logo.png

msix_config:
  display_name: Gizmo
  publisher_display_name: Hytech
  msix_version: 1.0.0.0
  languages: en-us
  logo_path: C:\Users\wilson\Desktop\new_project\gizmo_mobile\assets\icons\app_icon.png
  certificate_path: C:\Users\wilson\Desktop\new_project\gizmo_mobile\assets\certificate\GIZMO_CERTIFICATE.pfx
  certificate_password: 123456
  capabilities: "location,microphone,webcam"

  fonts:
    - family: Chivo
      fonts:
        - asset: assets/fonts/Chivo-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf

