// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'pandadoc_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PandadocData _$PandadocDataFromJson(Map<String, dynamic> json) => PandadocData(
      contractData: json['contractData'] == null
          ? null
          : ContractPandaData.fromJson(
              json['contractData'] as Map<String, dynamic>),
      status: json['status'] as int?,
    );

Map<String, dynamic> _$PandadocDataToJson(PandadocData instance) =>
    <String, dynamic>{
      'contractData': instance.contractData,
      'status': instance.status,
    };

ContractPandaData _$ContractPandaDataFromJson(Map<String, dynamic> json) =>
    ContractPandaData(
      template_id: json['template_id'] as String?,
      proposed_solar_panel: json['proposed_solar_panel'] as String?,
      proposed_battery: json['proposed_battery'] as String?,
      professional_engineering_fees:
          json['professional_engineering_fees'] as String?,
      nyserda_rebate: json['nyserda_rebate'] as String?,
      total_amount_due: json['total_amount_due'] as String?,
      second_payment: json['second_payment'] as String?,
      final_payment: json['final_payment'] as String?,
      final_payment_1: json['final_payment_1'] as String?,
      final_payment_note: json['final_payment_note'] as String?,
      final_payment_1_note: json['final_payment_1_note'] as String?,
      solar_pv_system_with_installation_price:
          json['solar_pv_system_with_installation_price'] as String?,
      proposed_work_title: json['proposed_work_title'] as String?,
      panel_count: json['panel_count'] as String?,
      proposed_microinverter: json['proposed_microinverter'] as String?,
      customer_name_1: json['customer_name_1'] as String?,
      first_name_1: json['first_name_1'] as String?,
      last_name_1: json['last_name_1'] as String?,
      first_name_2: json['first_name_2'] as String?,
      last_name_2: json['last_name_2'] as String?,
      customer_name_2: json['customer_name_2'] as String?,
      proposed_work_notes: json['proposed_work_notes'] as String?,
      permit_and_expediting_fees: json['permit_and_expediting_fees'] as String?,
      down_payment: json['down_payment'] as String?,
      payment_process_note: json['payment_process_note'] as String?,
      payment_process_note_footer:
          json['payment_process_note_footer'] as String?,
      roof_replacement_text: json['roof_replacement_text'] as String?,
      roof_replacement_note: json['roof_replacement_note'] as String?,
      additional_electrical_work: json['additional_electrical_work'] as String?,
      terms_and_conditions_notes: json['terms_and_conditions_notes'] as String?,
      proposal_id: json['proposal_id'] as String?,
      total_contract_price: json['total_contract_price'] as String?,
      customer_1_email: json['customer_1_email'] as String?,
      customer_1_address: json['customer_1_address'] as String?,
      customer_1_mobile: json['customer_1_mobile'] as String?,
      customer_2_email: json['customer_2_email'] as String?,
      customer_2_mobile: json['customer_2_mobile'] as String?,
      include_electrical_work: json['include_electrical_work'] as String?,
      include_roofing_work: json['include_roofing_work'] as String?,
      company_signer_first_name: json['company_signer_first_name'] as String?,
      company_signer_last_name: json['company_signer_last_name'] as String?,
      company_signer_email: json['company_signer_email'] as String?,
      deal_url: json['deal_url'] as String?,
      total_electrical_work: json['total_electrical_work'] as String?,
      total_roof_price: json['total_roof_price'] as String?,
      license_list: json['license_list'] as String?,
      terms_page3: json['terms_page3'] as String?,
      terms_page2: json['terms_page2'] as String?,
      terms_page1: json['terms_page1'] as String?,
      cancellation_notice: json['cancellation_notice'] as String?,
      reciept_acknowledgement: json['reciept_acknowledgement'] as String?,
      proposal_acceptance: json['proposal_acceptance'] as String?,
      payment_footprint: json['payment_footprint'] as String?,
      roofing_footprint: json['roofing_footprint'] as String?,
      customer_1_photo_id: json['customer_1_photo_id'] as String?,
      customer_2_photo_id: json['customer_2_photo_id'] as String?,
      customer_address: json['customer_address'] as String?,
      finance_option_header: json['finance_option_header'] as String?,
      finance_option_text: json['finance_option_text'] as String?,
      bridge_loan_header: json['bridge_loan_header'] as String?,
      bridge_loan_text: json['bridge_loan_text'] as String?,
      additional_projects_text: json['additional_projects_text'] as String?,
      additional_projects_pricing:
          json['additional_projects_pricing'] as String?,
    );

Map<String, dynamic> _$ContractPandaDataToJson(ContractPandaData instance) =>
    <String, dynamic>{
      'template_id': instance.template_id,
      'proposed_solar_panel': instance.proposed_solar_panel,
      'proposed_battery': instance.proposed_battery,
      'professional_engineering_fees': instance.professional_engineering_fees,
      'nyserda_rebate': instance.nyserda_rebate,
      'total_amount_due': instance.total_amount_due,
      'second_payment': instance.second_payment,
      'final_payment': instance.final_payment,
      'final_payment_1': instance.final_payment_1,
      'final_payment_note': instance.final_payment_note,
      'final_payment_1_note': instance.final_payment_1_note,
      'solar_pv_system_with_installation_price':
          instance.solar_pv_system_with_installation_price,
      'proposed_work_title': instance.proposed_work_title,
      'panel_count': instance.panel_count,
      'proposed_microinverter': instance.proposed_microinverter,
      'customer_name_1': instance.customer_name_1,
      'first_name_1': instance.first_name_1,
      'last_name_1': instance.last_name_1,
      'first_name_2': instance.first_name_2,
      'last_name_2': instance.last_name_2,
      'customer_name_2': instance.customer_name_2,
      'proposed_work_notes': instance.proposed_work_notes,
      'permit_and_expediting_fees': instance.permit_and_expediting_fees,
      'down_payment': instance.down_payment,
      'payment_process_note': instance.payment_process_note,
      'payment_process_note_footer': instance.payment_process_note_footer,
      'roof_replacement_text': instance.roof_replacement_text,
      'roof_replacement_note': instance.roof_replacement_note,
      'additional_electrical_work': instance.additional_electrical_work,
      'terms_and_conditions_notes': instance.terms_and_conditions_notes,
      'proposal_id': instance.proposal_id,
      'total_contract_price': instance.total_contract_price,
      'customer_1_email': instance.customer_1_email,
      'customer_1_address': instance.customer_1_address,
      'customer_1_mobile': instance.customer_1_mobile,
      'customer_2_email': instance.customer_2_email,
      'customer_2_mobile': instance.customer_2_mobile,
      'include_electrical_work': instance.include_electrical_work,
      'include_roofing_work': instance.include_roofing_work,
      'company_signer_first_name': instance.company_signer_first_name,
      'company_signer_last_name': instance.company_signer_last_name,
      'company_signer_email': instance.company_signer_email,
      'deal_url': instance.deal_url,
      'total_electrical_work': instance.total_electrical_work,
      'total_roof_price': instance.total_roof_price,
      'license_list': instance.license_list,
      'terms_page3': instance.terms_page3,
      'terms_page2': instance.terms_page2,
      'terms_page1': instance.terms_page1,
      'cancellation_notice': instance.cancellation_notice,
      'reciept_acknowledgement': instance.reciept_acknowledgement,
      'proposal_acceptance': instance.proposal_acceptance,
      'payment_footprint': instance.payment_footprint,
      'roofing_footprint': instance.roofing_footprint,
      'customer_1_photo_id': instance.customer_1_photo_id,
      'customer_2_photo_id': instance.customer_2_photo_id,
      'customer_address': instance.customer_address,
      'finance_option_header': instance.finance_option_header,
      'finance_option_text': instance.finance_option_text,
      'bridge_loan_header': instance.bridge_loan_header,
      'bridge_loan_text': instance.bridge_loan_text,
      'additional_projects_text': instance.additional_projects_text,
      'additional_projects_pricing': instance.additional_projects_pricing,
    };
